[package]
name = "kybra_generate"
version = "0.0.0"
edition = "2018"

[dependencies]
quote = "1.0.21"
syn = "1.0.99"
proc-macro2 = "1.0.43"
rustpython-parser = { git = "https://github.com/demergent-labs/RustPython", branch = "kybra_initial", default-features = false, features = [] }
annotate-snippets = "0.9.1"
num-bigint = "0.4.3"
# rustpython = { path = "../../../../RustPython", default-features = false, features = [] }
cdk_framework = { git = "https://github.com/demergent-labs/cdk_framework", rev = "c542015043cd68e62bb4a18e162ad6a379807e57" }
# cdk_framework = { path = "../../../../cdk_framework" } # For local rust-analyzer
# cdk_framework = { path = "../../../../../../../cdk_framework" } # For local deployment in kybra/examples
