[package]
name = "kybra_generate"
version = "0.0.0"
edition = "2018"

[dependencies]
quote = "1.0.21"
syn = "1.0.99"
proc-macro2 = "1.0.43"
regex = "1.7.0"
rustpython-parser = { git = "https://github.com/demergent-labs/RustPython", branch = "kybra_initial", default-features = false, features = [] }
annotate-snippets = "0.9.1"
num-bigint = "0.4.3"
# rustpython = { path = "../../../../RustPython", default-features = false, features = [] }
cdk_framework = { git = "https://github.com/demergent-labs/cdk_framework", rev = "df2a593d5c76312b66590591d64f477f474ebd46" }
# cdk_framework = { path = "/home/bdemann/code/demergent_labs/cdk_framework" } # For local rust-analyzer
# cdk_framework = { path = "../../../../../../../cdk_framework" } # For local deployment in kybra/examples
