[package]
name = "kybra-vm-value-derive"
version = "0.0.0"
edition = "2018"

[lib]
proc_macro = true

[dependencies]
quote = "1.0.17"
syn = "1.0.90"
proc-macro2 = "1.0.36"
cdk_framework = { git = "https://github.com/demergent-labs/cdk_framework", rev = "4e8e258046f9fb4e92e0e5015e14682d7d13d970" }
